-- AlterTable
ALTER TABLE "analyses" ADD COLUMN     "cls_score" INTEGER,
ADD COLUMN     "external_link_count" INTEGER,
ADD COLUMN     "fcp_ms" INTEGER,
ADD COLUMN     "h1_count" INTEGER,
ADD COLUMN     "h2_count" INTEGER,
ADD COLUMN     "h3_count" INTEGER,
ADD COLUMN     "has_csp" BOOLEAN,
ADD COLUMN     "has_hsts" BOOLEAN,
ADD COLUMN     "has_og_tags" BOOLEAN,
ADD COLUMN     "has_proper_heading_hierarchy" BOOLEAN,
ADD COLUMN     "has_twitter_card" BOOLEAN,
ADD COLUMN     "has_x_content_type_options" BOOLEAN,
ADD COLUMN     "has_x_frame_options" BOOLEAN,
ADD COLUMN     "images_with_alt" INTEGER,
ADD COLUMN     "internal_link_count" INTEGER,
ADD COLUMN     "lcp_ms" INTEGER,
ADD COLUMN     "performance_score" INTEGER,
ADD COLUMN     "structured_data_types" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "total_images" INTEGER,
ADD COLUMN     "ttfb_ms" INTEGER;
